### ISSUE TITLE
Cant Run Miner.dll

### ISSUE THREAD

**Issue by mbatchev** [guytp/burst-sharp#5]
When I try to run "dotnet ./Miner.dll" it just gives me this error message:

> Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
>   http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

 I think it might be because there is no file named Miner.dll anwhere in /burst-sharp or /burst-sharp/Miner as far as i'm aware. And the command dotnet ./miner.dll is looking for that file and can't find it.

Is it possible the actual file is missing from the repository? I installed it on two raspberry pis and both had same error...
Looking through the repo the miner.dll file is missing and after watching guy's video I see that he actually has a file named miner.dll
The way I installed this is by "git clone https://github.com/guytp/burst-sharp.git"
if that matters.

**Comment by mbatchev** [comment]
@guytp

**Comment by guytp** [comment]
@jumbodrawn you are trying to run the source code rather than the binaries.  You have a couple of options:

1. Download the binaries from the releases page https://github.com/guytp/burst-sharp/releases - if you get Miner-0.1.597.0.zip there should be all the files inside it - including Miner.dll - just checked and contents appear as BurstLib.dll BurstLib.pdb Miner.dll Miner.pdb miner-config.json Miner.deps.json Miner.runtimeconfig.json Newtonsoft.json.dll

2. Compile from source - to do this you need to have the full .Net Core 2.0.0 (not just runtime) and in the root directory of source with the .sln file do:

dotnet restore
dotnet build
dotnet run -p Miner

That should build the source locally and run it.  The config (and Mining.dll itself) will be in Miner\bin\Debug\netcoreapp2.0\

If this doesn't fix it, let me know

@jumbodrawn
